version: "3"

services:
  plumber_test:
    restart: unless-stopped
    image: rstudio/plumber
    container_name: plumber_test
    ports:
      - "8000:8000"
    volumes:
      - ./Code:/Code
    command: ["/Code/test.R"]
