version: "3"

services:
  plumber_test:
    restart: "no"
    build:
       context: .
       dockerfile: Dockerfile-ecadockerhub
    image: ecalab/rstudio_plumber:ecadockerhub
    container_name: plumber_test
    ports:
      - "8000:8000"
    volumes:
      - ./Code:/Code
      - ./Data:/Data
    command: ["/Code/test.R"]
