FROM rstudio/plumber
# Create a non-root user
# Please match this with host machine desired uid and gid
RUN groupadd -r --gid 901 ruser # 901 for ecadockerhub, 1000 for black
RUN useradd --no-log-init --uid 954 -r -m -g ruser ruser # 954 for ecadockerhub, 1000 for black
USER ruser
WORKDIR /home/ruser
RUN mkdir rlib
# install here all the packages you need
RUN R -e "install.packages('tidyverse', dependencies=TRUE, lib='rlib')"
RUN R -e "install.packages('writexl', dependencies=TRUE, lib='rlib')"
# add the new user repositories
ENV R_LIBS_USER="/home/ruser/rlib"
